package com.waesh.mindfulbell

const val PREF = "PREF_MINDFULLAPP"
const val PREF_ENABLED = "PREF_ENABLED"
const val PREF_SOUND_ENABLED = "PREF_SOUND_ENABLED"
const val PREF_NOTIFICATION_SOUND = "PREF_SOUND_ENABLED"
const val PREF_START_HOUR = "PREF_START_HOUR"
const val PREF_START_MINUTE = "PREF_START_MINUTE"
const val PREF_END_HOUR = "PREF_END_HOUR"
const val PREF_END_MINUTE = "PREF_END_MINUTE"
const val PREF_INTERVAL = "PREF_INTERVAL"

const val ACTION_RING_BELL_INTENT = "com.waesh.minfullbell.ACTION_RING_BELL_INTENT"